version: '3'

services:

  spring-boot-mysql:
    image: kerxd/spring-mysql-practica4
    
    environment:
      - SERVER_PORT=8080

    networks:
      - practica4-mysql

    ports:
      - "8080:8080"

    depends_on:
      - mysqldb3
      
      
  spring-boot-mysql-2:
    image: kerxd/spring-mysql-practica4
    
    environment:
      - SERVER_PORT=8081

    networks:
      - practica4-mysql

    ports:
      - "8081:8081"

    depends_on:
      - mysqldb3
      
      
  spring-boot-mysql-3:
    image: kerxd/spring-mysql-practica4
    
    environment:
      - SERVER_PORT=8082

    networks:
      - practica4-mysql

    ports:
      - "8082:8082"

    depends_on:
      - mysqldb3
      
      
      
  ha-proxy:
    image: haproxy:2.0.2
    networks:
      - practica4-mysql
    depends_on:
      - spring-boot-mysql
      - spring-boot-mysql-2
      - spring-boot-mysql-3

    ports:
      - 81:80
      
      

  mysqldb3:
    image: mysql:8

    networks:
      - practica4-mysql

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=practica4  
      
    volumes:
      - mysql_db:/var/lib/mysql
      
      
volumes:
  mysql_db:

networks:
  practica4-mysql:
