version: '3'

services:

  spring-boot-mysql:
    image: spring-mysql-practica4

    networks:
      - practica4-mysql

    ports:
      - "8080:8080"

    depends_on:
      - mysqldb3

  mysqldb3:
    image: mysql:8

    networks:
      - practica4-mysql

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=practica4  

networks:
  practica4-mysql:
